spring.application.name=raisetimeline

spring.datasource.url=jdbc:postgresql://localhost:5433/raisetimeline
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=5A7134743777217A25432A462D4A614E645267556B58703273357638792F423F
jwt.expiration=86400000

server.port=8080
